baseURL: ""
languageCode: en-us
title: Christy Bridgeman
theme: hugo-xmin

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Data
      url: "data/"
      weight: 2
    - name: Publishing
      url: "publishing/"
      weight: 3
    - name: Policy
      url: "policy/"
      weight: 4


params:
  description: "A website built through Hugo and blogdown."

  footer: "&copy; Christy Bridgeman {Year} | [GitHub](https://github.com/caBridgeman) | [LinkedIn](https://www.linkedin.com/in/Christy-EB)"
